const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({ viewport: {width:390,height:844} });
  const errors=[]; page.on('pageerror', e=>{errors.push(e.message);console.error('Page error:',e.message);});
  await page.goto('http://127.0.0.1:18085');
  await page.fill('#login-username','browser-admin');
  await page.fill('#login-password','test-password');
  await page.click('#login-form button');
  await page.locator('#admin-button').waitFor({state:'visible'});
  await page.click('[data-mode-button="IN"]');
  await page.fill('#scanner-input','00007777'); await page.press('#scanner-input','Enter');
  await page.locator('#unknown-form').waitFor({state:'visible'});
  await page.fill('#unknown-game-name','浏览器验收游戏'); await page.selectOption('#unknown-platform','PS5');
  await page.click('#unknown-form button[type="submit"]');
  await page.locator('#unknown-form').waitFor({state:'hidden'});
  await page.waitForFunction(()=>document.querySelector('#result').textContent.includes('库存 1'));
  await page.fill('#scanner-input','00007777'); await page.press('#scanner-input','Tab');
  await page.waitForFunction(()=>document.querySelector('#result').textContent.includes('库存 2'));
  let dropped = false;
  await page.route('**/api/scans', async route => {
    if (!dropped) { dropped = true; await route.fetch(); await route.abort(); }
    else await route.continue();
  });
  await page.fill('#scanner-input','00007777'); await page.press('#scanner-input','Enter');
  await page.locator('#retry-scan').waitFor({state:'visible'});
  await page.click('#retry-scan');
  await page.waitForFunction(()=>document.querySelector('#result').textContent.includes('库存 3'));
  await page.click('#exit-scan'); await page.click('#admin-button');
  await page.waitForFunction(()=>document.querySelector('#product-list').textContent.includes('库存 3'));
  await page.screenshot({path:'/tmp/game-inventory-admin.png',fullPage:true});
  await page.locator('#product-search summary').click();
  await page.fill('#product-search [name="q"]','00007777');
  await page.selectOption('#product-search [name="sales"]','none');
  await page.selectOption('#product-search [name="sort"]','quantity');
  await page.selectOption('#product-search [name="order"]','desc');
  await page.click('#product-search button[type="submit"]');
  await page.waitForFunction(()=>document.querySelector('#product-summary').textContent.includes('共 1 项'));
  await page.waitForFunction(()=>document.querySelector('#product-list').textContent.includes('期间出库 0 件'));
  await page.setViewportSize({width:320,height:740});
  if(await page.evaluate(()=>document.documentElement.scrollWidth > window.innerWidth)) throw new Error('Inventory page overflows mobile viewport');
  await page.click('#admin-back');
  await page.click('[data-mode-button="OUT"]');
  await page.fill('#scanner-input','00007777'); await page.press('#scanner-input','Enter');
  await page.waitForFunction(()=>document.querySelector('#result').textContent.includes('剩余 2'));
  await page.click('#exit-scan'); await page.click('#admin-button');
  await page.waitForFunction(()=>document.querySelector('#product-list').textContent.includes('没有符合条件'));
  await page.selectOption('#product-search [name="sales"]','low');
  await page.fill('#product-search [name="low_sales_max"]','1');
  await page.click('#product-search button[type="submit"]');
  await page.waitForFunction(()=>document.querySelector('#product-list').textContent.includes('期间出库 1 件'));
  await page.click('#inventory-reset');
  await page.waitForFunction(()=>document.querySelector('#product-list').textContent.includes('00007777'));
  await page.click('#admin-back'); await page.click('#reports-button');
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('#report-results tbody tr')).some(row => row.cells[1]?.textContent === '00007777' && row.cells[3]?.textContent === '1'));
  await page.selectOption('#report-period','custom');
  await page.fill('#report-start','2020-01-01'); await page.fill('#report-end','2020-01-02');
  await page.click('#reports-form button');
  await page.waitForFunction(()=>document.querySelector('#report-results').textContent.includes('没有销售'));
  await page.setViewportSize({width:320,height:740});
  if(await page.evaluate(()=>document.documentElement.scrollWidth > window.innerWidth)) throw new Error('Report page overflows mobile viewport');
  await page.click('#logout');
  await page.locator('#reports-panel').waitFor({state:'hidden'});
  if(await page.locator('#product-list').textContent()) throw new Error('Inventory retained after logout');
  if(await page.locator('#report-results').textContent()) throw new Error('Report retained after logout');
  if(errors.length) throw new Error(errors.join('\n'));
  console.log('Browser login, unknown resolution, Enter/Tab scans, lost-response idempotent retry and admin dashboard passed');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
